services:
  db:
    container_name: querycraft-db
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-querycraft}
      POSTGRES_USER: ${POSTGRES_USER:-querycraft}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-querycraft}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ollama:
    container_name: querycraft-ollama
    image: ollama/ollama:latest
    restart: unless-stopped
    entrypoint: ["/app/scripts/ollama-entrypoint.sh"]
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    environment:
      OLLAMA_HOST: 0.0.0.0
      OLLAMA_MODEL: sqlcoder:7b-q4_K_M
    volumes:
      - ollama_data:/root/.ollama
      - ./scripts:/app/scripts


volumes:
  postgres_data:
  ollama_data:
